version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - VPN_HOST=openvpn
      - VPN_PORT=1194
      
      - VPN_CLIENT_DIR=/etc/openvpn/client
      - HOTSPOT_TEMPLATE_DIR=/var/www/templates
    depends_on:
      - redis
    volumes:
      - .:/app
      - openvpn_client:/etc/openvpn/client
      - hotspot_templates:/var/www/templates
    networks:
      - app-network
    user: "1000:1000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=info --uid=1000
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - VPN_HOST=openvpn
      - VPN_PORT=1194
      - VPN_CLIENT_DIR=/etc/openvpn/client
      - HOTSPOT_TEMPLATE_DIR=/var/www/templates
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
      - openvpn_client:/etc/openvpn/client
      - hotspot_templates:/var/www/templates
    networks:
      - app-network
    user: "1000:1000"

networks:
  app-network:
    driver: bridge

volumes:
  openvpn_client:
  hotspot_templates:
  redis_data: 